theme = "neo"

[editor]
bufferline = "multiple"
cursorline = true
line-number = "relative"
rulers = [120]
color-modes = true
true-color = true
auto-save = true
scroll-lines = 1
auto-completion = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true

[editor.statusline]
left = [
  "mode",
  "spinner",
  "version-control",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
]
right = [
  "diagnostics",
  "separator",
  "selections",
  "primary-selection-length",
  "register",
  "position",
  "file-encoding",
  "separator",
  "file-type",
]

[editor.file-picker]
hidden = false

[keys.normal]
"C-/" = "toggle_comments"
"A-up" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
"A-down" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"tab" = "indent"
"S-tab" = "unindent"
"ret" = "insert_newline"
"backspace" = "delete_char_backward"

[keys.normal.space]
"q" = ":buffer-close"

[keys.normal."["]
"b" = "goto_previous_buffer"
"j" = "jump_backward"

[keys.normal."]"]
"b" = "goto_next_buffer"
"j" = "jump_forward"

[keys.insert]
"C-space" = "completion"
"tab" = ["move_next_long_word_start", "collapse_selection"]
"S-tab" = ["move_prev_long_word_start", "collapse_selection"]