[[language]]
name = "rust"

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "toml"
auto-format = true
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "swift"
